package dev.stefan.sokoban.ui.theme

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

/**
 * Every colour of the game, board included.
 *
 * The identity is warm and playful: sand floors, amber crates, a coral hero,
 * with slate walls and mint targets as the cool counterpoint. The dark palette
 * is designed separately, not inverted: walls get *lighter* than the floor so
 * the board keeps its relief, and crates and targets keep their saturation.
 */
@Immutable
data class Palette(
    val isDark: Boolean,
    val background: Color,
    val backgroundDeep: Color,
    val surface: Color,
    val surfaceRaised: Color,
    val outline: Color,
    val textPrimary: Color,
    val textSecondary: Color,
    val textMuted: Color,
    val accent: Color,
    val accentDeep: Color,
    val onAccent: Color,
    val floor: Color,
    val floorAlt: Color,
    val floorEdge: Color,
    val shadow: Color,
    val wallTop: Color,
    val wallFront: Color,
    val wallHighlight: Color,
    val goal: Color,
    val goalGlow: Color,
    val crate: Color,
    val crateDark: Color,
    val crateLight: Color,
    val crateDone: Color,
    val crateDoneDark: Color,
    val crateDoneLight: Color,
    val danger: Color,
    val player: Color,
    val playerDark: Color,
    val playerLight: Color,
    val eye: Color,
    val pupil: Color,
    val star: Color,
    val starEmpty: Color,
)

val LightPalette = Palette(
    isDark = false,
    background = Color(0xFFF5EEE3),
    backgroundDeep = Color(0xFFEADFCC),
    surface = Color(0xFFFFFAF2),
    surfaceRaised = Color(0xFFFFFFFF),
    outline = Color(0xFFE2D6C4),
    textPrimary = Color(0xFF2B2A35),
    textSecondary = Color(0xFF6B6573),
    textMuted = Color(0xFFA0988F),
    accent = Color(0xFFF0654F),
    accentDeep = Color(0xFFD24B37),
    onAccent = Color(0xFFFFFFFF),
    floor = Color(0xFFEBDFCB),
    floorAlt = Color(0xFFE4D6BF),
    floorEdge = Color(0xFFD3C1A5),
    shadow = Color(0xFF3B2E1E),
    wallTop = Color(0xFF45607F),
    wallFront = Color(0xFF2E4259),
    wallHighlight = Color(0xFF6582A5),
    goal = Color(0xFF2FB38A),
    goalGlow = Color(0xFF5FE0B5),
    crate = Color(0xFFF2A444),
    crateDark = Color(0xFFC77B24),
    crateLight = Color(0xFFFFD28A),
    crateDone = Color(0xFF34B98E),
    crateDoneDark = Color(0xFF218A68),
    crateDoneLight = Color(0xFF93EDCD),
    danger = Color(0xFFE5484D),
    player = Color(0xFFF0654F),
    playerDark = Color(0xFFC84634),
    playerLight = Color(0xFFFF9A86),
    eye = Color(0xFFFFFFFF),
    pupil = Color(0xFF2B2A35),
    star = Color(0xFFFFB938),
    starEmpty = Color(0xFFDCCFBC),
)

val DarkPalette = Palette(
    isDark = true,
    background = Color(0xFF161B26),
    backgroundDeep = Color(0xFF0E121A),
    surface = Color(0xFF1F2633),
    surfaceRaised = Color(0xFF283142),
    outline = Color(0xFF323C4F),
    textPrimary = Color(0xFFF3EDE4),
    textSecondary = Color(0xFFA9B1C2),
    textMuted = Color(0xFF6C7588),
    accent = Color(0xFFFF7A62),
    accentDeep = Color(0xFFE05B45),
    onAccent = Color(0xFFFFFFFF),
    floor = Color(0xFF2B3344),
    floorAlt = Color(0xFF283041),
    floorEdge = Color(0xFF1C2330),
    shadow = Color(0xFF000000),
    wallTop = Color(0xFF5A6F92),
    wallFront = Color(0xFF3B4B66),
    wallHighlight = Color(0xFF7B93B8),
    goal = Color(0xFF3FD3A2),
    goalGlow = Color(0xFF6BF0C2),
    crate = Color(0xFFEFA04A),
    crateDark = Color(0xFFB8742A),
    crateLight = Color(0xFFFFCD8A),
    crateDone = Color(0xFF3CC99A),
    crateDoneDark = Color(0xFF248E6C),
    crateDoneLight = Color(0xFF96F2D2),
    danger = Color(0xFFFF5A5F),
    player = Color(0xFFFF7A62),
    playerDark = Color(0xFFD0543F),
    playerLight = Color(0xFFFFAB98),
    eye = Color(0xFFFFFFFF),
    pupil = Color(0xFF1B2030),
    star = Color(0xFFFFC24D),
    starEmpty = Color(0xFF3A4456),
)

val LocalPalette = staticCompositionLocalOf { LightPalette }
